### ISSUE TITLE
OnSubscribeMap.java line 73

### ISSUE THREAD

**Issue by tevjef-crash** [tevjef/Rutgers-Course-Tracker#155]
#### in rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext

* Number of crashes: 396
* Impacted devices: 58

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/tevins-projects2/android/apps/com.tevinjeffrey.rutgersct/issues/57c8575c0aeb16625b8d3b10](https://fabric.io/tevins-projects2/android/apps/com.tevinjeffrey.rutgersct/issues/57c8575c0aeb16625b8d3b10)

**Comment by tevjef** [comment]
Non fatal. RMP server is down. Automatically switches to ondevice scraping.
